### PR TITLE
Use namespaced twig paths

### PR DESCRIPTION
**Pull request by deguif**
This is available since twig-bundle 2.2

### CODE REVIEW

**Comment by deguif** [comment]
It's also an issue in Symfony projects which use Twig engine directly without passing by the deprecated templating engine, as the old format is not supported.

**Comment by deguif** [comment]
It's also an issue in Symfony projects which use Twig engine directly without passing by the deprecated templating engine, as the old format is not supported.

**Comment by deguif** [comment]
@npotier any change to get this merged quickly, this is triggering errors on our side as we removed use of the templating engine to instead use twig directly?

**Comment by npotier** [comment]
Hello @deguif thank you for this PR. 

I trust you on this one, thank you for having updated the doc.

**Comment by npotier** [comment]
Thanks for the feedback 😄

**Pull request merged**
