### PR TITLE
Set primaryKeys in processMassActions if $actionAllKeys is selected

### PR DESCRIPTION
**Pull request by plfort**

### CODE REVIEW

**Comment by Abhoryo** [comment]
You don't have all keys so you can't do that.

**Comment by plfort** [comment]
Can you explain me why I don't have all keys ?

**Comment by Abhoryo** [comment]
Data is fetch per page so when you check the select all box, you can only get the id of the current page.

**Comment by plfort** [comment]
What about this code line 480:
```php
if ($actionAllKeys) {
                     $this->page = 0;
                     $this->limit = 0;
                 }
```
It disables pagination.
I manage to get all primary keys from the grid (with correct filters) with this PR

**Comment by plfort** [comment]
up ! :)

**Comment by hmert** [comment]
:+1:  @plfort :) I'll merge this, could you resolve the conflicts?

**Comment by hmert** [comment]
@plfort ping!

**Comment by plfort** [comment]
I'll work on it soon ;)

On Mon, Dec 14, 2015 at 10:52 PM, Hüseyin Mert <notifications@github.com>
wrote:

> @plfort <https://github.com/plfort> ping!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/APY/APYDataGridBundle/pull/718#issuecomment-164571094>
> .
>



-- 
FORT Pierre-Louis

**Pull request merged**
