### PR TITLE
Make easier the grid constructor with builder and factory pattern.

### PR DESCRIPTION
**Pull request by qferr**
See the [documentation](https://github.com/qferr/APYDataGridBundle/blob/2.3/Resources/doc/grid.md).

### CODE REVIEW

**Comment by hmert** [comment]
@qferr this new feature is very nice.
It's OK for merge, could you please resolve conflicts?

**Comment by delirehberi** [comment]
@qferr and please fix this bug: PHP Fatal error:  Can't use method return value in write context in /home/travis/build/APY/APYDataGridBundle/Grid/Grid.php on line 341

its problem on php5.4 and php5.3. , so you cant use function as `empty` function paramater.

**Comment by qferr** [comment]
@hmert, @delirehberi, 

Fixed. Sorry for ignoring PHP versions below 5.5...

**Comment by hmert** [comment]
@qferr still has conflicts

**Comment by qferr** [comment]
@hmert Resolved.

**Comment by nefthy** [comment]
This commit breaks backward compatibility, especialy when using the GridManager to create grids.

**Comment by qferr** [comment]
@delirehberi @nefthy I don't understand where this new feature breaks backward compatibility.

**Comment by clubdesarrolladores** [comment]
Can you create a new tag for this feature? (maybe 2.3)

**Comment by plfort** [comment]
@qferr The APY\DataGridBundle\Grid\Grid's constructor has changed.

**Comment by qferr** [comment]
@plfort, @delirehberi, @nefthy,

Alright. If I pass a null value for the grid configuration, it works ?

```php
    /**
     * Constructor
     *
     * @param Container $container
     * @param string    $id set if you are using more then one grid inside controller
     * @param GridConfigInterface $config The grid configuration.
     */
    public function __construct($container, $id = '', GridConfigInterface $config = null)
    {
    }
```

Of course, I fix the grid initialisation:

```php
    /**
     * {@inheritdoc}
     */
    public function initialize()
    {
        $config = $this->config;
        
        if (!$config) {
            return $this;
        }
```

**Comment by nefthy** [comment]
Ok, I'll try to explain a bit. In one of the applications I work on, the grid is created as follows:
```php
        $source = $source = new Grid\Source\Entity('Foo:Bar');
        ...
        $gridManager = $this->get('grid.manager');
        $grid = $gridManager->createGrid('xxx');
        $grid->setSource($source);
        $grid->setRouteUrl($this->generateUrl('yyy'));
```
that code worked fine before the merge of this pull requext. Now an Exception is thrown from some generated php file in the cache because of the constructor parameter change. I think the correct way to fix this would be to define the new parameters in the datagrid-bundle/Resources/config/services.xml (which already defines the first parameter), however my understunding of the dependency injection stuff is somewhat limited.

**Comment by qferr** [comment]
Ok. Thank you @nefthy. Sorry for this inconvenience. I've proposed one solution for this new feature doesn't break compatibility and if it's correct I pull a new request with the fix.

**Comment by hmert** [comment]
@b-durand @qferr I'll add both as maintainer. We missed this.

**Comment by plfort** [comment]
@qferr why don't create a default GridConfig and use it directly instead of copying parameters from $this->config to local Grid attribute ?

**Comment by qferr** [comment]
@b-durand This feature is tested for PHP 5.3

**Comment by qferr** [comment]
@plfort For don't break backward compatibility. In `3.0`, I would like to remove all local attributes and use directly the `GridConfigInterface`

**Pull request merged**
