### PR TITLE
filter on aggregated manytomany columns

### PR DESCRIPTION
**Pull request by FredDut**
When using string_agg on manytomany column, it would be appreciate to be able to filter.

Best regards.

### CODE REVIEW

**Comment by hmert** [comment]
@FredDut ping! :)

**Comment by FredDut** [comment]
@hmert pong? :-)

**Comment by hmert** [comment]
@FredDut time passed, could you rebase your PR? :) And it has broken some tests

**Comment by hmert** [comment]
This PR is dead and should rewrite. @APY/collaborators agree?

**Comment by FredDut** [comment]
Hello,
I'm not sure I understand everything, but if you need to rewrite the PR, it's OK.
Is "the PR is dead" means there's already a way to filter manytomany attributes?

**Comment by hmert** [comment]
@FredDut Hi, I think that it should rewrite or if it does not broke, it should be rebased. Do you have time for it?

**Comment by qferr** [comment]
Hi @FredDut,

If you rewrite this PR, can you add tests ?

Thank you

**Comment by FredDut** [comment]
Hi,
No, I don't have time and I don't know how to do it.
I think I mistake pull request for request for dev.
So you can remove it, if you want.

**Comment by hmert** [comment]
#798 this would be a good feature for `3.0`

**Pull request closed without merging**
