### PR TITLE
Handle anchor in grid route properly

### PR DESCRIPTION
**Pull request by mikvet**
if you use an anchor in the grid route like this:
$grid->setRouteUrl($this->generateUrl('some_route', $routeParamArray)."#anchor");
the anchor will be in the middle of the grid generated routes like this:
/some_route_url/#anchor?grid_params...
with this fix it is sent to the end, like this:
/some_route_url/?grid_params...#anchor
The regex takes care not to break # included in the url (which should be encoded as %23) and only take the words after the last #.

### CODE REVIEW

**Comment by hmert** [comment]
@APY/collaborators looks good for me :+1:

**Comment by qferr** [comment]
@mikvet Could you test this method ?

**Comment by mikvet** [comment]
Yes, BUT I just noticed it will break JS : grid_hash_resultsPerPage and grid_hash_goto as the js parameter are added at the end AFTER the anchor is added. I wrote a fix for this, I pass the string ' + limit + ' and ' + page + ' in the view as a parameter and use it in DataGridExtension like you already do with the page case: (I added $param to the limit case)
$prefix.Grid::REQUEST_QUERY_LIMIT.']='.$param.$suffix;
This is my first contribution (in all times) :-) I don't know how to commit the new version of these 2 files ? can you tell me how ? do I just create a new merge request and reject this one or is there a way to commit on this one ? thanks

**Comment by qferr** [comment]
Ok. Thank you for your contribution. Just push your new commits on this branch.

**Comment by mikvet** [comment]
just found out how to do :-) It works for me now

**Comment by qferr** [comment]
@mikvet Please fix this bug:

`APY\DataGridBundle\Tests\Twig\DataGridExtensionTest::testGetGridUrl
Object of class Mock_Column_d576194e could not be converted to string`

**Comment by hmert** [comment]
@mikvet are you free to fix this bug?

**Comment by mikvet** [comment]
I would like to, but my skills are to weak to debug the failed tests. I
don't understand the relation between my edit ant the failed tests and I
don't know how to run the tests on my environment :-) If somone can give me
a hing I'd be happy to finish this feature

Meilleures salutations.

Michael Vetterli

-- 
*Michael VETTERLI*
*Co-founder*
michael@idlab.ch
+41 76 413 53 36
+41 22 796 51 13

*Idlab - Développement d'applications web*
www.idlab.ch

**Comment by yazbahar** [comment]
@mikvet please add __toString method to `APY\DataGridBundle\Grid\Column\Column` class

**Comment by hmert** [comment]
@yazbahar please add __toString method to APY\DataGridBundle\Grid\Column\Column class after merging

**Comment by hmert** [comment]
@APY/collaborators please vote for merge

**Comment by mikvet** [comment]
Hi, the fix I made works on the JS links used in filters, order and number per page, is doesn't affect the links used in pagerfanta when enabled, these links are still wrong:
http://path?grid_id[_page]=#anchor2 instead of http://path?grid_id[_page]=2#anchor

**Comment by npotier** [comment]
I think we can close this PR because it is old an there is still an issue with PargerFanta.

Feel free to reopen the topic if "_having anchor in links_" becomes a very popular feature request.

**Pull request closed without merging**
