### PR TITLE
Replace deprecated Symfony "scope" service attributes by "shared" attributes

### LINKED ISSUE #780: grid.mapping.manager service scope
with **dev-master**

I know this was mentioned before [here](https://github.com/Abhoryo/APYDataGridBundle/pull/401) (and fixed?) but its still causing a deprecation warning in symfony 2.8

> The "scope" attribute of service "grid.mapping.manager" in file "/var/www/vhosts/project.dev/public_html/vendor/apy/datagrid-bundle/DependencyInjection/../Resources/config/services.xml" is deprecated since version 2.8 and will be removed in 3.0

### PR DESCRIPTION
**Pull request by deeky666**
Fixes #780

### CODE REVIEW

**Comment by deeky666** [comment]
Unfortunately we have to bump Symfony requirement to `^2.8` here to allow the usage of `shared` service attribute. Not sure how we could achieve BC here but as we step forward to making this compatible with Symfony 3.0, we need to bump anyways.

**Comment by qferr** [comment]
@deeky666 I'm sorry, this PR break BC and cannot be merge in `2.3. If you want to merge, please remove the symfony requirement `2.8`. Thank you

**Comment by deeky666** [comment]
@qferr so which version do you aim to be Symfony 3 compatible then? If you want to achieve compat with Symfony 3, we have to use `shared` and that is only available since 2.8.

**Comment by qferr** [comment]
Indeed, I propose to ask @APY/collaborators whether the version 2.3 should use the symfony version 2.8.

**Comment by deeky666** [comment]
@qferr thanks. I will provide another PR that fixes the remaining Symfony deprecations and then this bundle should be Symfony 3 ready.

**Comment by hmert** [comment]
@deeky666 We should not merge this PR for 2.3 because it'll break the BC.

-1 for me.

**Comment by deeky666** [comment]
@hmert I'm fine with not merging into 2.3 as long as there will be a Symfony 3 compatible branch people can use. As people are currently upgrading to Symfony 3, this should be a goal to achieve rather sooner than later IMO as it prevents people from upgrading. Any plans on this?

**Comment by deeky666** [comment]
@hmert could you provide some info about the maintenance policy for Symfony versions? I don't think it makes sense to support every Symfony 2.x version. We could eventually get compatible with Symfony 3 by bumping only to `2.6` (which is the least requirement for `Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface` that has to be used instead of the removed `Symfony\Component\Security\Core\SecurityContext`). As `2.6` is already EOL according to Symfony's release process, that would be fairly acceptable IMO.

**Comment by hmert** [comment]
@deeky666 `APYDataGridBundle@2.3` should work on `Symfony<2.8`. I hope, It will reach the state of a bug-free, that's why we want to maintenance the project. And only `2.3.x` versions will be released for bug fixes.

And I think that we will mostly rewrite whole project at `3.x` which works on `Symfony^2.8`. And my plan is APY's release should be synced with Symfony.

This is my opinion @APY/collaborators should also write theirs.

**Comment by deeky666** [comment]
@hmert I totally get your standpoint and it sounds very reasonable. The only downside I see with this is that a rewrite will most likely take some time, so people wanting to upgrade to Symfony 3.0, will have to wait quite a lonh time. What about having `2.3.x` as bug fix maintenance only branch for `Symfony <2.8` and another `2.4.x` being maintained (bugfix only) in parallel which only differs in the way that it is Symfony 3.0 compatible. `master` would be the `3.0` rewrite development branch then. This way, everybody could be satisfied without a big development overhead IMO. But that's just my 2 cents :)

**Comment by giovkanata** [comment]
I agree with @deeky666 +1

**Comment by hoshsadiq** [comment]
+1 on @deeky666's approach

**Comment by npotier** [comment]
This PR is outdated and should be closed

**Pull request closed without merging**
