### PR TITLE
Disable the Output walkers of Entity with joins (Fixes #931)

### LINKED ISSUE #931: The Paginator does not support Queries which only yield ScalarResults.
Hi,
I'm using symfony 3.1.10 with APY 3.0.0
When I use this, to get field from another table using Entity as SOURCE:
`@GRID\Column(field="login.username",safe=false,title="Dish Name")`

throw the error:
`The Paginator does not support Queries which only yield ScalarResults.`

I look inside the code and if in the File located in:
/datagrid-bundle/Grid/Source/Entity.php
I replace this:
       
```
        $this->prepareQuery($this->query);
        $hasJoin = $this->checkIfQueryHasFetchJoin($this->query);

        $query = $this->query->getQuery();
        foreach ($this->hints as $hintKey => $hintValue) {
            $query->setHint($hintKey, $hintValue);
        }
        
        $items = new Paginator($query, $hasJoin);

        $repository = $this->manager->getRepository($this->entityName);
```

with this (so revert this piece of to code to 2.3.0)
```
        $this->prepareQuery($this->query);

        $hasJoin = $this->checkIfQueryHasFetchJoin($this->query);
        $query = $this->query->getQuery()
        foreach ($this->hints as $hintKey => $hintValue) {
            $query->setHint($hintKey, $hintValue);
        }
        $items = $query->getResult();
        $repository = $this->manager->getRepository($this->entityName);
```

So replace 
`$items = new Paginator($query, $hasJoin); `
with  
`$items = $query->getResult();`

It works correctly

### PR DESCRIPTION
**Pull request by StudioMaX**
Fix for issue #931 
There is another pull request #939 , but it will revert the functionality added by commit #828

### CODE REVIEW

**Comment by DonCallisto** [comment]
@hmert I've seen you merged #828. Can you take a look to this?

**Comment by Vowow** [comment]
Pealse merge this one

**Comment by DonCallisto** [comment]
@Vowow Waiting for maintainer of the bundle to check if everything it's ok. I can merge it too but I'm not into all bundle logic and, without test cases, I can't judge if this is good or not. 
However I would expected more commitment from new maintainers .... /cc @hmert

**Comment by hmert** [comment]
@DonCallisto and @Vowow I could not figure out why we're removing walkers. But, in our project. I've tested this PR it looks OK.

**Comment by DonCallisto** [comment]
@StudioMaX can you explain this change to @hmert ?

**Comment by Vowow** [comment]
@hmert This provide a fix to a bug when you add a manyToOne column to the grid with annotation.
The error is : "The Paginator does not support Queries which only yield ScalarResults. "

**Comment by StudioMaX** [comment]
@hmert can you release a new version?

**Pull request merged**
