### PR TITLE
Add template to RowAction

### PR DESCRIPTION
**Pull request by plfort**
This PR provides an easy way to customize RowAction rendering by adding a template to the RowAction.
The default template is unchanged.
I will add documentation if you think this PR is ok.

### CODE REVIEW

**Comment by Abhoryo** [comment]
No need for this. I don't think this is easier this way.

**Comment by plfort** [comment]
Ok but how can I customize rendering of row action ? for example if I want to use  as label ?

**Comment by Abhoryo** [comment]
Like other columns you can override its template.
If you don't want to change the grid_column_actions_cell template you can change the title of the action column.

**Comment by plfort** [comment]
Yes, I don't want to use the title of the action to put html in it.
And "grid_column_actions_cell" does not satisfy me because I want to customize a given RowAction and not the global cell rendering. Another solution would be to add an "id" to the RowAction to distinguish it in the "grid_column_actions_cell" loop.
I don't think this PR generate BC.

**Comment by Abhoryo** [comment]
Sorry my last comment wans't correct.
See this doc : https://github.com/Abhoryo/APYDataGridBundle/blob/master/Resources/doc/grid_configuration/add_actions_column.md

You can create your own actionColumn with a differente id.

**Comment by plfort** [comment]
Indeed, but I need an id on the RowAction not on the Column to customize RowAction rendering.
I think it lacks the RowAction level in the template.

**Comment by plfort** [comment]
Can I contact you by mail ? So we can talk in French : )
Maybe I am not very clear with my explanations

**Comment by Abhoryo** [comment]
Désolé, je suis occupé ces derniers temps.
Je comprends pas où est vraiment le problème.
Je suis d'accord que ca oblige a changer un template de la colonne action mais y a que 2/3 lignes en trop par rapport au rendu de la row action.

Sinon quitte à mettre un système pour le rendu, il faudrait utiliser le même qu'ailleurs, donc un bloc plutôt qu'un template externe.

**Comment by plfort** [comment]
Oui je suis d'accord il faudrait utiliser le même système de block, cela nécessiterait d'avoir un id par RowAction afin d'avoir un block du style "grid_column_actions_rowaction_%id%" a surcharger. Peut être en ajoutant cet id en paramètre de la méthode addRowAction.

**Comment by Abhoryo** [comment]
Oui en utilisant une nouvelle fonction dans DataGridExtension.php je suppose.

**Comment by delirehberi** [comment]
if @Abhoryo no need this, sorry :(

**Pull request closed without merging**
