### PR TITLE
Updates to theme config and ajax

### PR DESCRIPTION
**Pull request by pierredup**
This PR has 2 parts:

1. Update the javascript to load only the grid block instead of the whole page
2. Allow setting a default custom theme from the config

Related: #348, #272

### CODE REVIEW

**Comment by hmert** [comment]
This PR is dead also. Agree @APY/collaborators ?

**Comment by pierredup** [comment]
I haven't tested on the latest version of this bundle, but if it is still an issue with the ajax calls, then I can try and re-do this PR

**Comment by hmert** [comment]
Thank you, I haven't tested too. I'll make a sandbox on the latest version to test ajax calls

**Comment by hmert** [comment]
let's close this PR, we have no issues about ajax calls so far.

**Comment by hmert** [comment]
thank you @pierredup

**Pull request closed without merging**
