### PR TITLE
Fixed PHPUnit tests

### PR DESCRIPTION
**Pull request by DonCallisto**
This should fix https://github.com/APY/APYDataGridBundle/pull/877

However we should bump PHPUnit version and write more tests.
What remain to complete SF3 step?

### CODE REVIEW

**Comment by DonCallisto** [comment]
Should it be compatible with php 5.4?
I don't think so (test will fail due to `::class` syntax)

**Comment by DonCallisto** [comment]
As predicted, Travis fails only with 5.4 PHP version

**Comment by hmert** [comment]
@DonCallisto we already deprecated 5.4, 5.5. Only 5.6 may supported.

**Comment by DonCallisto** [comment]
@hmert ok, so Travis should not run on 5.4 and 5.5

However test now pass: what should we do to complete migrations to sf3?

**Comment by hmert** [comment]
I will remove 5.4 from travis now. My bad, I forget this line. https://github.com/APY/APYDataGridBundle/blob/master/.travis.yml

**Comment by hmert** [comment]
@DonCallisto could you rebase from master?

**Comment by DonCallisto** [comment]
@hmert what should I rebase? This branch or whole symfony3 branch? Because I checked out from symfony3 branch so, imho, it has sense to rebase whole sf3 branch and then this (if necessary). Otherwise conflicts will still be there I suppose.
If symfony3 branch needs to be rebased with master I'm afraid that's your task because I really don't know commits in that branch, even if I can try to do it.

Let me know.

**Comment by hmert** [comment]
@DonCallisto from Sf3 branch.  We will merge sf3 to master if it does not fails from tests.

Our aim for this bundle works with both 2.8 and 3.x

**Comment by DonCallisto** [comment]
@hmert I've seen you have merged master into symfony3 this morning. So I'm gonna rebase to symfony3 and resolve conflicts. Is this ok for you?

**Comment by hmert** [comment]
@DonCallisto sure! :) thank you

**Comment by DonCallisto** [comment]
@hmert here you are!

however, although I've changed only tests and deprecations (along with CS), you should try the bundle onto a demo (if you have) because, ATM, I don't have a significant installation to test "manually" on.

**Comment by hmert** [comment]
we have https://github.com/ojs/ojs :) it is full usage of apy

**Comment by DonCallisto** [comment]
@hmert yes, well, maybe it's better to test locally first so I was asking :)

**Pull request merged**
