### PR TITLE
Add TWIG2 fix

### PR DESCRIPTION
**Pull request by phenixiim**

### CODE REVIEW

**Comment by DonCallisto** [comment]
This fix https://github.com/APY/APYDataGridBundle/issues/913 however, I'm not sure if we should merge this into master as twig 2 could BC. Maybe is better to integrate this in symfony3 branch? BTW I've lost this release, didn't we tagged the new version? @hmert

**Comment by hmert** [comment]
We've released `2.3.0` but composer file points as it is `>=1.23.0` We've already BC.

**Comment by DonCallisto** [comment]
Ok, so we can integrate this PR I guess and I guess it's a good idea to integrate it also in symfony3 branch, isn't it?

Will you take care of this?

**Comment by hmert** [comment]
Yes, sure.

**Comment by hmert** [comment]
It seems that it is already fixed at `symfony3`.
https://github.com/APY/APYDataGridBundle/blob/symfony3/Twig/DataGridExtension.php#L386-L415

**Comment by phenixiim** [comment]
Sorry guys, I did not notice that, thanks for info and trash this PR.

Thanks for such a good work!

S přátelským pozdravem a přáním hezkého dne / Best regards
Dalibor Jaroš
+420 773 740 852

Dne 09/01/2017 v 16:36 Hüseyin Mert napsal(a):

**Comment by hmert** [comment]
@phenixiim thank you anyway.

**Comment by DonCallisto** [comment]
@hmert @phenixiim what's funny is that's from a PR of mine (https://github.com/APY/APYDataGridBundle/commit/ab47d7d6116090481e78e8bef2d4cf95f723dba5#diff-2bab4ca7a557b4ec05d1c2b696fc323aR389) 

Memory starts to fail 😄

**Pull request closed without merging**
