### PR TITLE
Typo fix in prepareColumnValues typings

### PR DESCRIPTION
**Pull request by teklakct**

### CODE REVIEW

**Comment by teklakct** [comment]
@DonCallisto can you find some time for this?

**Comment by DonCallisto** [comment]
@teklakct can you squash all commits into single one? thanks.

**Comment by teklakct** [comment]
@DonCallisto no problem, but I think you can squash it during merge.

**Comment by DonCallisto** [comment]
@teklakct I know but I wish you to do so you can also edit commit message.

**Comment by teklakct** [comment]
@DonCallisto done

**Pull request merged**
