### PR TITLE
Test improvement

### PR DESCRIPTION
**Pull request by DonCallisto**
Issue ref.: https://github.com/APY/APYDataGridBundle/issues/906

This should be used to track progress about tests

Grid
- [x] Columns
- [x] Filter
- [x] Grid
- [x] GridBuilder
- [x] GridConfigBuilder
- [x] GridFactory
- [x] GridManager
- [x] GridRegistry
- [x] Row
- [x] Rows

Action
- [x] DeleteMassAction
- [x] MassAction
- [x] RowAction

Column
- [x] BlankColumn
- [x] BooleanColumn
- [x] DateColumn
- [x] MassActionColumn
- [x] RankColumn
- [x] TextColumn
- [x] TimeColumn
- [x] UntypedColumn
- [x] JoinColumn
- [x] DateTimeColumn
- [x] NumberColumn
- [x] SimpleArrayColumn
- [x] ArrayColumn
- [x] ActionsColumn
- [x] Column

Exception
- [x] ColumnAlreadyExistsException
- [x] ColumnNotFoundException
- [x] TypeAlreadyExistsException
- [x] TypeNotFoundException
- [x] UnexpectedTypeException
- [x] InvalidArgumentException

Export
- [ ] CSVExport
- [ ] DSVExport
- [ ] ExcelExport
- [ ] Export
- [ ] JSONExport
- [ ] PHPExcel5Export
- [ ] PHPExcel2003Export
- [ ] PHPExcel2007Export
- [ ] PHPExcelHTMLExport
- [ ] PHPExcelPDFExport
- [ ] SCSVExport
- [ ] TSVExport
- [ ] XMLExport

Helper
- [x] ColumnsIterator
- [ ] ORMCountWalker

Mapping
- [x] Column
- [x] Source
- [ ] Annotation
- [x] DriverHeap
- [x] Manager
- [x] Metadata

Source
- [x] Document
- [ ] Entity
- [ ] Source
- [ ] Vector

### CODE REVIEW

**Comment by DonCallisto** [comment]
I've also add coveralls to keep an eye to progress of coverage (that's not our goal, but is a good indicator to check progress)

**Comment by hmert** [comment]
@DonCallisto any new updates? :)

**Comment by DonCallisto** [comment]
@hmert if you take a look, you can notice that I'm working on it only in the week ends. By now we have nearly 19% of code covered by UT.
My last commit was done two days ago: unfortunately this is the only free time I can dedicate to this bundle at the moment.
If someone would like to join me and help with tests is welcome! :)

**Comment by DonCallisto** [comment]
For everyone interested in contributing, I'm going to start  `Grid` test that will require some times I guess. If anyone would like to pick other tests, feel free to do it and write it down here.

**Comment by AlessandroMinoccheri** [comment]
To all contributors, I'm going to start `Grid/Mapping` test.

**Comment by AlessandroMinoccheri** [comment]
To all contributors, I'm going to start Grid/Source test

**Comment by DonCallisto** [comment]
A little update: I've finish the tests for `Grid` file which is the biggest file in our bundle. Hopefully coverage will have a boost of ~ 20%, reaching 50%.
Hopefully, now that I'm "in the zone" and I have speed up testing process a lot, 50 % left out should be covered in a short term period.
Moreover we have @AlessandroMinoccheri's PR ready about `Source\Entity`: if no improvement needed in this, coverage should increase of another ~ 10%

**Comment by DonCallisto** [comment]
To all contributors, I'm taking `GridManager` as next test

**Comment by AlessandroMinoccheri** [comment]
Ok, I hope to close early my PR to continue with another class

**Comment by DonCallisto** [comment]
@AlessandroMinoccheri let me know when you're ready to discuss it

**Comment by AlessandroMinoccheri** [comment]
I think that in this week we can start to review It

**Comment by DonCallisto** [comment]
To all contributor: I'm taking `Source\Document` --> https://github.com/APY/APYDataGridBundle/pull/958

**Comment by DonCallisto** [comment]
I've merged `Source\Document` PR even if it's not at 100% as I'm not aware of any method to check expectations on cloned stub/mocks.

If anyone is aware of this, please, share or - better - open a PR with tests on non-covered code.
Thanks.

I'm gonna take `Source\Vector` next.

**Pull request merged**
