### PR TITLE
Revert "Make easier the grid constructor with builder and factory pattern."

### PR DESCRIPTION
**Pull request by delirehberi**
Reverts APY/APYDataGridBundle#782

### CODE REVIEW

**Comment by qferr** [comment]
Why ?

**Comment by delirehberi** [comment]
@qferr https://github.com/APY/APYDataGridBundle/pull/782#issuecomment-164474751

**Comment by plfort** [comment]
+1

**Comment by b-durand** [comment]
@delirehberi you can rebase without overwriting my commit 9a8a8cd0e1bd7f31cc59bf131984db7e29f3b8e6.

**Comment by hmert** [comment]
@qferr Does this break bc? if not, we should not revert. You may continue to fix with a new PR.

@b-durand @plfort I'll also added both as maintainer. Please accept if you want to join the swarm :bee:

**Comment by hmert** [comment]
:bomb:

**Pull request closed without merging**
